default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost
  password: 123

development:
  <<: *default
  database: tarea4

test:
  <<: *default
  database: tarea4_test

production:
  <<: *default
  database: tarea4_production